# Playbook file: Automates the deployment of setup.sh on Manages Nodes

- name: Execute Deployment Script
  hosts: ManagedNode1
  become: yes

  tasks:    
    - name: Ensure correct permission for /vagrant directory
      file:
        path: /vagrant
        state: directory
        mode: '0755'
        owner: vagrant
        group: vagrant
          
    - name: Copy Deployment Script
      copy:
        src: /vagrant/Deployments/setup.sh
        dest: /home/vagrant/setup.sh
        mode: '0755'

    - name: Remove CRLF characters if present
      replace:
        path: /home/vagrant/setup.sh
        regexp: '\r$'
        replace: ''
      when: ansible_check_mode == false  # Skip this task in check mode

    - name: Ensure setup.sh is executable
      file:
        path: /home/vagrant/setup.sh
        mode: '0755'
        owner: vagrant
        group: vagrant
        state: file
      when: ansible_check_mode == false  # Skip this task in check mode

    - name: Execute Deployment Script
      shell: /home/vagrant/setup.sh >> /vagrant/ansible.log 2>&1
      args:
        executable: /bin/bash
      when: ansible_check_mode == false  # Skip this task in check mode

    - name: Create uptime.log and set permissions for uptime.log file
      file:
        path: /vagrant/uptime.log
        state: touch
        mode: '0644'

    - name: Create a cron job to check the server's uptime every 1 am
      cron:
        name: "Log server uptime"
        minute: "0"
        hour: "1"
        job: "uptime >> /vagrant/uptime.log"
        user: vagrant
