# Playbook file: Automates the deployment of setup.sh on Manages Nodes

- name: Execute Deployment Script
  hosts: ManagedNode1
  become: yes

  tasks:
    - name: Copy Deployment Script
      copy:
        src: ./setup.sh
        dest: /tmp/setup.sh
        mode: 0775

    - name: Execute Deployment Script
      shell: /tmp/setup.sh >> /vagrant/ansible.log 2>&1

    - name: Set permission for /vagrant directory
      file:
        path: /vagrant
        state: directory
        mode: 0775   
        owner: vagrant
        group: vagrant
      when: not ansible_check_mode

    - name: Create uptime.log and set permissions for uptime.log file
      file:
        path: /vagrant/uptime.log
        state: touch
        mode: 0644
      when: not ansible_check_mode

    - name: Create a cron job to check the server's uptime every 1 am
      cron:
        name: "Log server uptime"
        minute: "0"
        hour: "1"
        job: "uptime >> /vagrant/uptime.log"
        user: vagrant
